name: merge

on:
  push:
    branches: master
    paths:
      - "merge/*"
      - .github/workflows/merge.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: merge
          file: merge/Dockerfile
          tags: ghcr.io/flathub/actions/merge:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
